#!/bin/bash
# SessionStart hook — prepares the Docker stack for Claude Code on the web.
#
# In a remote (web) session this:
#   1. starts the Docker daemon (the container ships dockerd but doesn't auto-start it),
#   2. logs in to Docker Hub from $DOCKERHUB_USERNAME / $DOCKERHUB_TOKEN so image
#      pulls aren't blocked by the unauthenticated per-IP rate limit, and
#   3. writes a local-only docker-compose.override.yml that feeds the sandbox's
#      egress-proxy CA into the image build as a BuildKit secret, so in-build
#      `npm ci` / `pip install` can verify TLS through the intercepting proxy.
#
# Everything here is gated to remote sessions and is a no-op when the relevant
# inputs are absent, so it's safe to run on any machine. Nothing it does touches
# tracked files (the override is git-ignored) or leaks the token to disk in plain
# sight beyond Docker's own ~/.docker/config.json.
set -uo pipefail

# Local dev machines manage their own Docker — only run in Claude Code on the web.
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

log() { echo "[session-start] $*" >&2; }

# ── 1. Docker daemon ──────────────────────────────────────────────────────────
if ! docker info >/dev/null 2>&1; then
  log "starting dockerd…"
  setsid dockerd >/tmp/dockerd.log 2>&1 &
  for _ in $(seq 1 30); do
    docker info >/dev/null 2>&1 && break
    sleep 1
  done
fi
if docker info >/dev/null 2>&1; then
  log "dockerd is up"
else
  log "WARNING: dockerd did not come up; see /tmp/dockerd.log"
fi

# ── 2. Docker Hub auth (no-op if creds absent) ────────────────────────────────
# The token env var can arrive with stray surrounding whitespace; trim it.
DOCKERHUB_TOKEN_TRIMMED="$(printf '%s' "${DOCKERHUB_TOKEN:-}" | tr -d '[:space:]')"
if [ -n "${DOCKERHUB_USERNAME:-}" ] && [ -n "$DOCKERHUB_TOKEN_TRIMMED" ]; then
  if printf '%s' "$DOCKERHUB_TOKEN_TRIMMED" \
       | docker login -u "$DOCKERHUB_USERNAME" --password-stdin >/dev/null 2>&1; then
    log "docker login OK as $DOCKERHUB_USERNAME"
  else
    log "WARNING: docker login failed for $DOCKERHUB_USERNAME"
  fi
else
  log "Docker Hub creds not set; skipping login (pulls may hit the anon rate limit)"
fi

# ── 3. Proxy-CA build secret (local-only compose override) ────────────────────
# The sandbox MITMs TLS; only the host trusts the egress CA, so build containers
# can't verify pypi/npm. Hand the full host CA bundle to the build as a secret.
CA_BUNDLE="${SSL_CERT_FILE:-/etc/ssl/certs/ca-certificates.crt}"
OVERRIDE="$CLAUDE_PROJECT_DIR/docker-compose.override.yml"
if [ -r "$CA_BUNDLE" ]; then
  cat > "$OVERRIDE" <<EOF
# AUTO-GENERATED by .claude/hooks/session-start.sh — DO NOT COMMIT (git-ignored).
# Feeds the sandbox egress-proxy CA into the image build so in-build npm/pip can
# verify TLS through the intercepting proxy. Regenerated each remote session.
services:
  web:
    build:
      context: .
      secrets:
        - proxy_ca
secrets:
  proxy_ca:
    file: $CA_BUNDLE
EOF
  log "wrote $OVERRIDE (proxy_ca <- $CA_BUNDLE)"
else
  log "no readable CA bundle at $CA_BUNDLE; skipping build-secret override"
fi

exit 0
