apiVersion: 1

datasources:
  - name: Postgres
    uid: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: tensies
    secureJsonData:
      password: tensies
    jsonData:
      database: tensies
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true
