/* Build the tensies-ui bindings package:
   1. Generate src/assets.generated.ts (data URIs for the repo's brand SVGs +
      a QR placeholder) so previews and designs are self-contained.
   2. esbuild src/index.ts → dist/index.js (ESM, react external).
   3. tsc --emitDeclarationOnly → dist/*.d.ts.
   4. Assemble dist/tensies.css from the app's REAL stylesheets
      (static/css, index.html order, a2hs excluded) with font URLs rewritten
      to ./fonts/ (copied alongside) and the board poster inlined as a data
      URI. The CSS is the app's, byte-for-byte apart from those URL rewrites. */

import { execSync } from 'node:child_process';
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, '..', '..');
const STATIC = join(REPO, 'static');
const DIST = join(HERE, 'dist');

// ── 1. Generated assets ──
const svgUri = (p) =>
  `data:image/svg+xml;base64,${readFileSync(join(STATIC, 'images', p)).toString('base64')}`;

// Deterministic QR-ish placeholder (finder squares + pseudo-random modules).
function qrPlaceholder() {
  let seed = 7;
  const rand = () => ((seed = (seed * 1103515245 + 12345) % 2147483648) / 2147483648);
  const N = 21;
  let cells = '';
  const finder = (x, y) =>
    `<rect x="${x}" y="${y}" width="7" height="7" fill="#1a1a1a"/><rect x="${x + 1}" y="${y + 1}" width="5" height="5" fill="#fff"/><rect x="${x + 2}" y="${y + 2}" width="3" height="3" fill="#1a1a1a"/>`;
  for (let y = 0; y < N; y++) {
    for (let x = 0; x < N; x++) {
      const inFinder = (x < 8 && y < 8) || (x >= N - 8 && y < 8) || (x < 8 && y >= N - 8);
      if (!inFinder && rand() > 0.55) cells += `<rect x="${x}" y="${y}" width="1" height="1" fill="#1a1a1a"/>`;
    }
  }
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 21 21"><rect width="21" height="21" fill="#fff"/>${cells}${finder(0, 0)}${finder(14, 0)}${finder(0, 14)}</svg>`;
  return `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`;
}

writeFileSync(
  join(HERE, 'src', 'assets.generated.ts'),
  `/* GENERATED by build.mjs from static/images — do not edit. */
export const LOGO_SVG_URI = ${JSON.stringify(svgUri('logo.svg'))};
export const LOGO_WINNER_SVG_URI = ${JSON.stringify(svgUri('logo-winner.svg'))};
export const AVATAR_DEFAULT_URI = ${JSON.stringify(svgUri('avatar-default.svg'))};
export const QR_PLACEHOLDER_URI = ${JSON.stringify(qrPlaceholder())};
`,
);

// ── 2 + 3. Bundle + declarations ──
mkdirSync(DIST, { recursive: true });
const run = (cmd) => execSync(cmd, { cwd: HERE, stdio: 'inherit' });
run(
  'npx esbuild src/index.ts --bundle --format=esm --jsx=automatic ' +
    '--external:react --external:react-dom --external:react/jsx-runtime ' +
    '--outfile=dist/index.js',
);
run('npx tsc -p tsconfig.json');

// ── 4. CSS + fonts ──
// index.html order, minus a2hs.css (install-banner chrome tied to marketing
// imagery — not part of the component design language).
const CSS_FILES = [
  'critical.css',
  'controls.css',
  'shell.css',
  'sheet.css',
  'landing.css',
  'lobby.css',
  'stamp.css',
  'nearby.css',
  'game.css',
  'players-bar.css',
  'dice.css',
  'menu.css',
  'overlays.css',
  'auth.css',
  'profile.css',
  'game-detail.css',
];

mkdirSync(join(DIST, 'fonts'), { recursive: true });
const FONTS = [
  'inter-latin-variable.woff2',
  'ebgaramond-latin-variable.woff2',
  'rye-latin.woff2',
  'yellowtail-latin.woff2',
];
for (const f of FONTS) copyFileSync(join(STATIC, 'fonts', f), join(DIST, 'fonts', f));

const posterUri = `data:image/webp;base64,${readFileSync(join(STATIC, 'video', 'poster-game.webp')).toString('base64')}`;

let css = CSS_FILES.map((f) => `/* ── static/css/${f} ── */\n${readFileSync(join(STATIC, 'css', f), 'utf8')}`).join('\n\n');
css = css
  .replaceAll("url('/static/fonts/", "url('./fonts/")
  .replaceAll("url('/static/video/poster-game.webp')", `url('${posterUri}')`);

const leftover = css.match(/url\(['"]?\/static\/[^)]+\)/g);
if (leftover) {
  console.error(`! unrewritten /static/ url(s) in CSS:\n  ${[...new Set(leftover)].join('\n  ')}`);
}
writeFileSync(join(DIST, 'tensies.css'), css);

console.error(`built dist/: index.js + d.ts + tensies.css (${CSS_FILES.length} sheets) + ${FONTS.length} fonts`);
